### ISSUE TITLE
Convert existing cPanel docs to MD

### ISSUE THREAD

**Issue by phillf** [opencad-app/OpenCAD-docs#5]
https://github.com/opencad-app/OpenCAD-docs/tree/89da1f817c7f3690af2f82119e7537fc45e0dd72

**Comment by Cambridgeport90** [comment]
I never saw this... so using [Code Butify](https://codebeautify.org/html-to-markdown) for the basic conversions and then editing the headings and what not; the formatting is initially a mess when it comes out of there.

**Comment by Cambridgeport90** [comment]
#16
